# Generated by Django 5.2.4 on 2025-08-12 00:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
