# Generated by Django 5.2.4 on 2025-08-13 00:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
