# Generated by Django 5.2.4 on 2025-08-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
