# Generated by Django 5.2.4 on 2025-08-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_comentario'),
        ('posts', '0005_post_imagen'),
    ]

    operations = [
    ]
