# Generated by Django 5.2.4 on 2025-07-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='cont_comentario',
        ),
    ]
