# Generated by Django 5.2.4 on 2025-08-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_comentario_nom_autor_comentario_com_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ('-fecha_publicacion',)},
        ),
    ]
